### ISSUE TITLE
Difference between TOWR ?

### ISSUE THREAD

**Issue by littleggghost** [rcywongaa/humanoid#5]
Hi @rcywongaa 
After running the examples, I want to know the difference between this repo and Towr.
This repo and Towr compute the footholds and GRFs in future times, and running without physics engine or collision with environments.  
The difference is this repo use Drake, and use meshcat to visualize, the Towr use Xpp to visualize. 
Am I right?

**Comment by rcywongaa** [comment]
Well, aside from the obvious fact that TOWR works and this repo hardly works... 🤣 

I encourage you to read both papers
1. Gait and Trajectory Optimization for Legged Systems Through Phase-Based End-Effector Parameterization by Alex et al. (this paper is implemented in TOWR)
1. Whole-body Motion Planning with Centroidal Dynamics and Full Kinematics by Hongkai et al. (this paper is implemented, to some degree, in this repo)
I think they are reasonably easy to read.
Basically, they formulate the optimization problem differently, hence have different benefits and tradeoffs.

A couple of notable difference (from what I remember):
- In Gait and Trajectory Optimization for Legged Systems Through Phase-Based End-Effector Parameterization, only the center of mass position and orientation and foot positions are calculated.  The required joint torques / values afterwards.  This has the benefit that it produces a simpler optimization problem which can be solved much faster.  The drawback is that since the full kinematic model isn't present in the formulation, joint limits and torque limits cannot be enforced directly.  In the case of joint limits, this is solved by approximating the feet reachable spaces instead.  Also, the optimization problem cannot take into account collision due to the kinematics not being part of the program.  Hence, the optimizer can generate body and foot positions that would require other robot links to collide with the environment.  
- In Whole-body Motion Planning with Centroidal Dynamics and Full Kinematics, the full kinematics (every joint) is part of the optimization problem.  This results in a much more complicated optimization problem that may take longer to solve but does not suffer from the drawbacks of the other paper.

**Comment by littleggghost** [comment]
Thanks so much for your very detailed answer! 
Before give more questions, I will follow the papers first.
